### ISSUE TITLE
Updating data from square to circle

### ISSUE THREAD

**Issue by rmckeel** [novus/nvd3#1005]
Using a stock NVD3 scatterChart, can't transition from one square data point to one circle data point without error messages in Chrome (likely other browsers also).

Chrome presents this message (with transitions disabled), and the circle data point is nowhere to be seen:
```
Error: Invalid value for <path> attribute d="M0,2.256758334191025A2.256758334191025,2.256758334191025 0 0.9999999999999999,1 0,-2.256758334191025A2.256758334191025,2.256758334191025 0 1,1 0,2.256758334191025Z"
```

If transitions are allowed to play out, get this:
```
Error: Invalid value for <path> attribute d="M-2.683133198261887,-0.8942529430451149A-0.8942529430451149,-2.6830084085530395 0.8943777327539624 -0.8943224367539623,2.683188494261887 0.8943777327539624,0.8942529430451149A2.6832579879707343,-0.8942529430451149 0.8943777327539624 -2.683077902261887,1 0,2.256758334191025Z"(anonymous function) @ d3.min.js:5c @ d3.min.js:2(anonymous function) @ d3.min.js:2_t @ d3.min.js:1Mt @ d3.min.js:1
d3.min.js:5 Error: Invalid value for <path> attribute d="M-2.6359383539808126,-0.8388283794590046A-0.8388283794590046,-2.596120615446213 0.8786461179936041 -0.8610023419936041,2.6535821299808124 0.8786461179936041,0.8388283794590046A2.675756092515412,-0.8388283794590046 0.8786461179936041 -2.6182945779808127,1 0,2.256758334191025Z"(anonymous function) @ d3.min.js:5c @ d3.min.js:2_t @ d3.min.js:1Mt @ d3.min.js:1
d3.min.js:5 Error: Invalid value for <path> attribute d="M-2.4049250694126116,-0.5675315741653626A-0.5675315741653626,-2.1708149537737707 0.8016416898042039 -0.6979043458042039,2.508662413412612 0.8016416898042039,0.5675315741653626A2.639035185051453,-0.5675315741653626 0.8016416898042039 -2.301187725412612,1 0,2.256758334191025Z"(anonymous function) @ d3.min.js:5c @ d3.min.js:2_t @ d3.min.js:1Mt @ d3.min.js:1
d3.min.js:5 Error: Invalid value for <path> attribute d="M-1.8417749341434713,0.09381927795022438A0.09381927795022438,-1.134030678145423 0.6139249780478238 -0.3003139700478238,2.155385942143471 0.6139249780478238,-0.09381927795022438A2.5495191901415195,0.09381927795022438 0.6139249780478238 -1.5281639261434714,1 0,2.256758334191025Z"(anonymous function) @ d3.min.js:5c @ d3.min.js:2_t @ d3.min.js:1Mt @ d3.min.js:1
d3.min.js:5 Error: Invalid value for <path> attribute d="M-0.9142906300576412,1.1830359830795656A1.1830359830795656,0.5735088963744714 0.3047635433525471 0.3545004566474531,1.5735546300576415 0.3047635433525471,-1.1830359830795656A2.402090156489754,1.1830359830795656 0.3047635433525471 -0.25502663005764115,1 0,2.256758334191025Z"(anonymous function) @ d3.min.js:5c @ d3.min.js:2_t @ d3.min.js:1Mt @ d3.min.js:1
d3.min.js:5 Error: Invalid value for <path> attribute d="M-0.3015414302180197,1.9026348610118329A1.9026348610118329,1.7016072408664864 0.10051381007267324 0.7871083339273265,1.1891635742180193 0.10051381007267324,-1.9026348610118329A2.3046901013025254,1.9026348610118329 0.10051381007267324 0.5860807137819801,1 0,2.256758334191025Z"(anonymous function) @ d3.min.js:5c @ d3.min.js:2_t @ d3.min.js:1Mt @ d3.min.js:1
d3.min.js:5 Error: Invalid value for <path> attribute d="M-0.054614955014270716,2.192619759457877A2.192619759457877,2.1562097894483636 0.01820498500475687 0.9614412229952428,1.0342611630142702 0.01820498500475687,-2.192619759457877A2.265439699476904,2.192619759457877 0.01820498500475687 0.925031252985729,1 0,2.256758334191025Z"(anonymous function) @ d3.min.js:5c @ d3.min.js:2_t @ d3.min.js:1Mt @ d3.min.js:1
d3.min.js:5 Error: Invalid value for <path> attribute d="M-0.0005007647402779369,2.2561702473435736A2.2561702473435736,2.255836404183388 0.00016692158009268265 0.9996464544199076,1.0003141407402787 0.00016692158009268265,-2.2561702473435736A2.2568379336639444,2.2561702473435736 0.00016692158009268265 0.9993126112597226,1 0,2.256758334191025Z"(anonymous function) @ d3.min.js:5c @ d3.min.js:2_t @ d3.min.js:1Mt @ d3.min.js:1
d3.min.js:5 Error: Invalid value for <path> attribute d="M0,2.256758334191025A2.256758334191025,2.256758334191025 0 0.9999999999999999,1 0,-2.256758334191025A2.256758334191025,2.256758334191025 0 1,1 0,2.256758334191025Z"
```

Unfortunately, I don't have the time right now to build out a simplified code sample, so I'm hoping this information alone helps.

**Comment by RenatoUtsch** [comment]
Are you sure your data is correct? This usually happens when you set invalid x/y/size values. Your acessor functions can be wrong too.

**Comment by rmckeel** [comment]
Quite sure - I used the stock 'RandomData' function e.g. ```randomData(1,1)``` as the source, then changed to ```randomData(1,1)``` with a different shape.

**Comment by liquidpele** [comment]
Are you using the latest code from the development branch?

**Comment by rmckeel** [comment]
I was not.  Do you have a simple jsbin/jsfiddle starting template I could fork that links to the dev branch? Perhaps I can replicate and share through that method.

**Comment by liquidpele** [comment]
not on hand, there have been several used in past issues though if you look... mostly using rawgit.com to pull the development branch code from github for it.

**Comment by liquidpele** [comment]
I'm assuming this is fixed in latest... please let us know if not.

**Comment by wwhurley** [comment]
I'm still seeing that using the build on https://github.com/novus/nvd3/commit/4d51a332ac79a2fa0e79983091acada4103f2273. It is intermittent so it's hard to figure out where it's coming from. For example:
```
d3.min.js?o5kzbp:4 Error: Invalid value for <path> attribute d="M-2.6749238163536835,-0.8635243019781418A-0.8635243019781418,-2.6468068462139307 0.8916412721178945 -0.8885265201178945,2.6780385683536836 0.8916412721178945,0.8635243019781418A2.7030407864934363,-0.8635243019781418 0.8916412721178945 -2.6718090643536834,1 0,9.0270333367641Z"
```
