### ISSUE TITLE
controlLabels doesn't work at nvd3.org/livecode and with multiBarHorizontalChart

### ISSUE THREAD

**Issue by mqklin** [novus/nvd3#1411]
I just put this line in the [examples](http://nvd3.org/livecode/index.html) to `Group / Stacked Bar Chart` and to `Horizontal Grouped / Stacked Bar Chart` and it breaks: `chart.controlLabels({"grouped":"Group em","stacked":"Stack em"});`.

Moreover, it works with `multiBarChart` in my code, but not with `multiBarHorizontalChart`. It just becomes renamed, but doesn't work (like in #756 issue).

I've created PR: #1412

**Comment by liquidpele** [comment]
Fixed in PR.

**Comment by mqklin** [comment]
@liquidpele , but it still doesn't work in `livecode`. What the version of `nvd3` there? May be it will work after update?

**Comment by liquidpele** [comment]
Yea it'll have to be updated after next release.  I need to rebuild too, but on mobile and out of town at the moment :)

**Comment by mqklin** [comment]
Okay
