### ISSUE TITLE
Resizing chart breaks tooltip pointers when starting x values are not 0

### ISSUE THREAD

**Issue by alexssung** [novus/nvd3#1777]
Currently on 1.8.4, resizing a chart causes the tooltip pointers (the circles that highlight the data points under the cursor) to not follow the correct scale.

Example:
http://plnkr.co/edit/Vr02uC0kx3jrpghcamMh?p=preview

Resize the window or drag the column to trigger a resize of the chart, then hover your cursor over the chart and notice the tooltip pointers are not behaving correctly.

I just spent several hours trying to figure out the cause of this issue, and I finally noticed that if the data set starts with x: 0 (e.g. [{x: 0, y: 1}, {x: 1, y: 2},...]), then this issue does not occur. This issue only happens when the starting x is not 0.

To verify, change the i=1 to i=0 in the script.js of the plunkr provided above, and find that resizing the chart works fine.

Any ideas for workarounds for when one needs to start the data set with x > 0 ? Such as when we are plotting against the days of the month.

**Comment by mgalloue** [comment]
+1

**Comment by liquidpele** [comment]
reproduce steps:
1. view the plunker, then resize the frame that the chart shows so it's much wider. 
2. hover the mouse over, the circles points that show up do not stay on the interactive guideline, they hover over to the side of it as if their offset calculation is based on the previous width of the chart and not the new width. 

Yea that is weird... is this new to 1.8.4?

**Comment by mgalloue** [comment]
@liquidpele yes, it was working with the previous version.

**Comment by liquidpele** [comment]
Interesting... if you can locate what PR caused it i can revert it...

**Comment by mgalloue** [comment]
I think the issue come from [Semi-Modular implementation of focus charts](https://github.com/novus/nvd3/commit/706f28b71ff93e2df23d6175971deecf0092ac26) PR, but didn't test it.

**Comment by mgalloue** [comment]
Mmm I just remember this discussion [Optimise scatter model](https://github.com/novus/nvd3/pull/1378), maybe this is related...

**Comment by liquidpele** [comment]
Huh, you seem to reference this exact issue in that PR but it looks like they fixed it, so I wonder what happened?

**Comment by mgalloue** [comment]
@ThomasBrierley is it possible that there is still an issue with #1378 ? Do you have any idea on whats happen?

**Comment by ThomasBrierley** [comment]
Yeah this is dup of @mgalloue's bug, fixed in #1758 but there haven't been any releases since it was merged (v1.8.4 doesn't contain the fix).

Here's @alexssung's example working with the latest build pasted over the CDN:

http://plnkr.co/edit/RUxo5tB5N12V3WyKCIvf?p=preview

**Comment by liquidpele** [comment]
Ah okay, so it's just waiting for the next release.   I'm about to make the next release, just waiting on a few things to wrap up.

**Comment by mgalloue** [comment]
@liquidpele @ThomasBrierley, I have the fixe on my side and still seeing the issue on another example..

**Comment by mgalloue** [comment]
Maybe on my side it's another scenario, I'm wondering if it's could come from [Semi-Modular implementation of focus charts](https://github.com/novus/nvd3/commit/706f28b71ff93e2df23d6175971deecf0092ac26)..

**Comment by ThomasBrierley** [comment]
@mgalloue Could you post a test case using the latest build?

**Comment by mgalloue** [comment]
@ThomasBrierley I'm on a really specific scenario not easy to reproduce outside my environnement. The only think I know it's that this issue doesn't exist with last release, appears with 1.8.4 release and is still here with the last build ;-/

**Comment by ThomasBrierley** [comment]
I know it's crude but you can probably narrow it down through a manual binary search with the code... Try and remove half of the code at a time (leaving the half with the stuff you care about without removing the behaviour or breaking it).

Or If you can remove anything you don't want to share I can probably isolate it for you.

**Comment by liquidpele** [comment]
https://github.com/novus/nvd3/pull/1817 might have fixed, can someone verify lastest master?

**Comment by mehranshakeri** [comment]
It seems fixed in version "1.8.4-dev 2016-09-26"

**Comment by liquidpele** [comment]
sweeeeeeeeeeeet
