### ISSUE TITLE
useInteractiveGuideline points missing or mispositioned

### ISSUE THREAD

**Issue by Federico-G** [novus/nvd3#1865]
I upgraded from 1.8.1 to 1.8.4 yesterday, to fix a bug with the interactive guideline, but now I have another one

I use the example from https://nvd3-community.github.io/nvd3/examples/site.html (LineWithFocusChart in particular, but the problem is in any graph that use useInteractiveGuideline)
When you don't have all series selected, the points of some series are missing or mispositioned.

![captura de pantalla de 2016-11-11 18-29-41](https://cloud.githubusercontent.com/assets/6208777/20231676/677c5ce2-a842-11e6-91ae-66fb290de7cf.png)
Even when it's only one left:
![captura de pantalla de 2016-11-11 18-30-08](https://cloud.githubusercontent.com/assets/6208777/20231678/67811890-a842-11e6-8655-57fe3c79f134.png)

When all series are selected works OK:
![captura de pantalla de 2016-11-11 18-29-52](https://cloud.githubusercontent.com/assets/6208777/20231677/677dbd12-a842-11e6-8971-22ad3e894ddc.png)

Tested in: _Mozilla Firefox 45.4 ESR_ and _Chrome 54.0_ (Ubuntu 16.04)

**Comment by liquidpele** [comment]
Pretty sure this is fixed in latest Master branch

**Comment by Federico-G** [comment]
Testing with 1.8.4-dev (2016-10-02) in my own site

It seems that there are no more missing points, but this still happens **sometimes**:
![screenshot 2016-11-14 15-59-50](https://cloud.githubusercontent.com/assets/6208777/20278486/bad80222-aa83-11e6-9047-1d7d08d41da5.png)


After some tests, we discover that this happens only when the Y scale changes; and the mispositioned point is, in fact, in the same position as before
![screenshot 2016-11-14 16-05-01](https://cloud.githubusercontent.com/assets/6208777/20279243/927b0808-aa86-11e6-8ea1-dca009d98753.png)
![screenshot 2016-11-14 16-05-17](https://cloud.githubusercontent.com/assets/6208777/20279248/94c940e8-aa86-11e6-8fbc-4af6e226f10f.png)

One more thing, in the last image, the second X is blue instead of orange, shouldn't it be the same color?

Thanks

**Comment by dadagama** [comment]
👍   exactly the same error. even if you do not change Y scale.
you can reproduce it in this plunkr:
http://plnkr.co/edit/lBKFld?p=preview
change nvd3 version from **1.8.1**  to **1.8.4** and then select only 1 or 2 series from the legend.
you will see the missing of points

**Comment by Federico-G** [comment]
@dadagama. I use the master version for all of this tests. In master version I don't have missing points, they are sometimes misspositioned.

I submit a test with my own data:
https://jsbin.com/lidukag/
To test it, you only have to deselect the orange serie ([V2]). The serie [V1] has all their points misspositioned, exactly the original position in the chart before deselect [V1]

![screenshot 2016-11-29 16-33-06](https://cloud.githubusercontent.com/assets/6208777/20725962/7259bac4-b652-11e6-9d00-97ccbfeb7df8.png)

**Comment by ThomasBrierley** [comment]
Hi @Federico-G I've tested the above fix in your fiddle and the issue is no longer present.

**Comment by Federico-G** [comment]
@ThomasBrierley I think it's fixed. Thank you! I close it, and wait for #1880 to be merged

**Comment by liquidpele** [comment]
Merged, it's in 1.8.5-dev now.
