### ISSUE TITLE
multiChart: voronoi messes up in Firefox when using a line on both axis. 

### ISSUE THREAD

**Issue by amelzer** [novus/nvd3#804]
I stumbled upon a problem when trying to use a multichart for two line graphs. The tooltips in the second line graph (red one in the following example) are not always shown when hovering over the data points. However, they seem to work on some occasion (but never on all datatypes). This occurs in Firefox but not in Chrome.

I stripped down the multichart example from this repository to illustrate the point.

```javascript
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link href="../build/nv.d3.css" rel="stylesheet" type="text/css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>
    <script src="../build/nv.d3.js"></script>
    <script src="lib/stream_layers.js"></script>

    <style>
        text {
            font: 12px sans-serif;
        }
        svg {
            display: block;
        }
        html, body, #chart1, svg {
            margin: 0px;
            padding: 0px;
            height: 100%;
            width: 100%;
        }
    </style>
</head>
<body class='with-3d-shadow with-transitions'>

<div id="chart1" >
    <svg> </svg>
</div>

<script>

    var testdata = stream_layers(7,10+Math.random()*100,.1).map(function(data, i) {
        return {
            key: 'Stream' + i,
            values: data.map(function(a){a.y = a.y * (i <= 1 ? -1 : 1); return a})
        };
    });

    testdata[2].type = "line";
    testdata[2].yAxis = 1;
    testdata[3].type = "line";
    testdata[3].yAxis = 2;


    nv.addGraph(function() {
        var chart = nv.models.multiChart()
            .margin({top: 30, right: 60, bottom: 50, left: 70})
            .color(d3.scale.category10().range());

        chart.xAxis.tickFormat(d3.format(',f'));
        chart.yAxis1.tickFormat(d3.format(',.1f'));
        chart.yAxis2.tickFormat(d3.format(',.1f'));

        d3.select('#chart1 svg')
            .datum(testdata)
            .transition().duration(500).call(chart);

        return chart;
    });

</script>
</body>
</html>
```

**Comment by robinfhu** [comment]
Grrrr...seems like every issue these days revolve around tooltips :-(

**Comment by liquidpele** [comment]
![allthetooltips](http://i.imgur.com/qr39Z7Q.jpg)

**Comment by amelzer** [comment]
I guess I came a little bit closer to the problem today.
When using two axes, the "tooltip-hover-zones" for the right axis graph are somehow vertically located on the left axis graph.

![hover-zones](https://cloud.githubusercontent.com/assets/1628866/6258928/4585e106-b7cd-11e4-82ba-8f9c82540ba5.png)

I think it has to do with duplicate IDs. When using two y-axes, ids for nv-edge-clip, nv-path, nv-point-clips, nv-point-click are reused which leads to problems in FF but not in Chrome.

**Comment by wojteklenny** [comment]
I have the same problem. http://jsfiddle.net/ab79r879/ 
Seems like tooltips for green line are shown in some cases when hovering over blue line.
Any chance for fixing this soon?

**Comment by robinfhu** [comment]
@liquidpele is doing lots of work on tooltips right now.

**Comment by liquidpele** [comment]
This should be fixed now I think.   https://github.com/novus/nvd3/pull/851

**Comment by wojteklenny** [comment]
I've just checked dev barnch and still have the same problem and some new errors when using tooltipContent method now.

**Comment by liquidpele** [comment]
I forgot to built latest too... I just a second ago built it and pushed it up so you can just use the files in the "build" directory of the development branch.  Sorry and can you check again please?

**Comment by wojteklenny** [comment]
I build it by myself, but can check your build to be sure. Just a second.

**Comment by wojteklenny** [comment]
Yep, unfortunately I can confirm, still does not work for me with tooltips and new errors when using tooltipContent.

**Comment by liquidpele** [comment]
Yes, tool tip content is deprecated.  Errors are expected if you're using that... Use chart.tooltip.contentGenerator and note the passed data structures a different (more generic)

**Comment by liquidpele** [comment]
Okay, I reproduce this using this jsfiddle:   http://jsfiddle.net/ab79r879/5/

Basically, in chrome it positions the voronoi areas correctly, but in FF it overlaps them for the line on the right axis for some reason... very weird.  This is an issue with the voronoi calculation and not tooltips.  Re-opening this.

**Comment by liquidpele** [comment]
I think the major issue here is that we're creating two distinct voronoi layers, we should really only be creating one, or overlaps are going to still be issues regardless...

**Comment by robinfhu** [comment]
Just a side note, we don't need voronoi...period.  Didn't nvd3 community update scatter.js so that each point was surrounded by an invisible circle, which was supposed to replace the voronoi boxes?

**Comment by liquidpele** [comment]
Nope, we never moved from voronoi.  You really do need it for a lot of points though, otherwise the hover will be really weird when the circles/whatever are all overlapping due to multiple lines overlapping.

**Comment by robinfhu** [comment]
Yes you are right

**Comment by huttli** [comment]
These two commits solved my problem on dual line tooltip voronoi on Firefox and IE.
Possibly fix on this issue?

https://github.com/embertec-eng/nvd3/commit/f3d85f05e6508f8ba32ee2f22db57fb13d5705ad
https://github.com/embertec-eng/nvd3/commit/d93bc516c76ef4d95bfad91f8bdd08d858912a6b

**Comment by liquidpele** [comment]
I think both those items are actually fixed in master already, done pretty recently... feel free to verify and if not, send up a pull request.   If you can verify that everything works well now (I didn't realize those fixes might solve this issue too) then let us know and we can close this issue as well :)

**Comment by leo-117** [comment]
Bugfix for cleaning the remaining tooltips 

--- Typescript ---

`private static idTooltipsCleaner = null;

/**
     * It is responsible for cleaning the remaining tooltips
     */
    if (myComponent.idTooltipsCleaner === null) {
      myComponent.idTooltipsCleaner = setInterval(() => {
        const tooltips = $('.nvtooltip');
        if (tooltips) {
          /**
           * All except the last, since it represents
           * the tooltip of the current graph
           */
          for (let i = 0; i < (tooltips.length - 1); i++) {
            $('#' + tooltips[i].id).remove();
          }
        }
      }, 750);
    }`
