### ISSUE TITLE
xAxis.axisLabel not centered for multiBarHorizontalChart

### ISSUE THREAD

**Issue by vbsql7** [novus/nvd3#823]
The left-hand vertical text is the issue. It shows up, but at the very top of the chart instead of being nicely centered like the bottom axis label is.

In the code, the xAxis and yAxis are opposite because this is a 'horizontal' bar chart. 

![screen shot 2015-02-27 at 3 31 01 pm](https://cloud.githubusercontent.com/assets/9969712/6420641/cd7733de-be95-11e4-820c-492db178acd3.png)

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link href="nv.d3.css" rel="stylesheet" type="text/css">
    <script src="d3.min.js" charset="utf-8"></script>
    <script src="nv.d3.min.js"></script>

    <style>
        text {
            font: 12px sans-serif;
        }
        svg {
            display: block;
        }
        html, body, #chart1, svg {
            margin: 5px;
            padding: 0px;
            height: 100%;
            width: 100%;
        }
    </style>
</head>
<body>

<div id="chart1" >
<svg></svg>
</div>
<script>

// Create fake data stream
function generateData ( ) {
  var numberOfPoints = 10,
      graphData = [],
      j;

    series = [];
    for (j = 0; j < numberOfPoints; j++) {
      graphData.push({label: 'Item ' + String(j), value: (Math.random() * 100)});
    }
  
  return graphData;
}

// Format data stream as JSON
var dataToGraph = [
  {
    key: 'Series 1',
    color: '#1f77b4',
    values: generateData()
  }
]

// Create chart 
var chart;
var svg;

svg = d3.select('#chart1 svg');

nv.addGraph(function() {

  chart = nv.models.multiBarHorizontalChart()
  .x(function(d) { return d.label })
  .y(function(d) { return d.value })
  .noData('Not enough data to graph')
  .barColor(['lightsalmon', 'indianred'])
  .duration(250)
  .showValues(true)
  .showControls(false)
  ;

  // Add Y axis label
  chart.yAxis
    .axisLabel('Y axis label')
    .tickFormat(d3.format(',.0f'))
    ;

  chart.xAxis.axisLabel('Things'); // not centered, but present and floats with resize

  svg.datum(dataToGraph).call(chart);

  nv.utils.windowResize(chart.update);

  chart.dispatch.on('stateChange', function(e) { nv.log('New State:', JSON.stringify(e)); });

  chart.state.dispatch.on('change', function(state){
    nv.log('state', JSON.stringify(state));
    });

  return chart;

}); 


// Add chart title
var width = document.getElementById("chart1").offsetWidth;
svg
  .append("text")
  .attr("x", (width/2)-20)             
  .attr("y", 25)
  .attr("text-anchor", "middle")  
  .style("font-size","22px")
  .style("font-weight","bold")
  .text("Chart Title");

</script>
</body>
</html>
	
```

**Comment by liquidpele** [comment]
Weird.  Verified in latest code.

**Comment by liquidpele** [comment]
Okay, I fixed that, see the above pull request, just waiting on review.

**Comment by jscheid** [comment]
Hi, this still appears to be an issue when the chart contains only few bars, see:

https://jsfiddle.net/julians37/sygr5bvy/1/

The larger the value of `numberOfPoints` near the top, the more centered it is, but for low values it's noticeably off center.

**Comment by jscheid** [comment]
I'm getting good results by calculating `x` the same as for the `top` and `bottom` cases, i.e.:

```javascript
w = 0;
if (scale.range().length === 1) {
  w = isOrdinal ? scale.range()[0] * 2 + scale.rangeBand() : 0;
} else if (scale.range().length === 2) {
  w = isOrdinal ? scale.range()[0] + scale.range()[1] + scale.rangeBand() : scale.range()[1];
} else if ( scale.range().length > 2){
  w = scale.range()[scale.range().length-1]+(scale.range()[1]-scale.range()[0]);
};
axisLabel.attr('x', -w/2);
```

Is there a reason `x` is calculated differently for the left and right cases?
